whitelist:
  - com.alipay.sofa.rpc.codec.fury.model.whitelist.*
  - com.alipay.sofa.rpc.codec.fury.model.Registered.*


register:
  - com.alipay.sofa.rpc.codec.fury.model.Registered.DemoRequest
  - com.alipay.sofa.rpc.codec.fury.model.Registered.DemoResponse
  - com.alipay.sofa.rpc.codec.fury.model.Registered.HelloService
  - com.alipay.sofa.rpc.codec.fury.model.Registered.HelloServiceImpl
  - com.alipay.sofa.rpc.codec.fury.model.Registered.RegisteredClass

blacklist:
  - com.alipay.sofa.rpc.codec.fury.model.blacklist.*